### ISSUE TITLE
error sorting GTF

### ISSUE THREAD

**Issue by trakhtenberg** [ctokheim/PrimerSeq#44]
I use this command: python2.7 gtf.py -i input.gtf -o sorted.gtf
I get this error:
Traceback (most recent call last):
  File "gtf.py", line 128, in <module>
    sort_gtf(args.gtf, args.output)  # do the work of sorting
  File "gtf.py", line 57, in sort_gtf
    gtf = Gtf(gtf_line)
  File "gtf.py", line 30, in **init**
    self.seqname, self.source, self.feature, self.start, self.end, self.score, self.strand, self.frame, self.attribute = gtf_line  # These indexes are defined by the GTF spec
ValueError: need more than 1 value to unpack

**Comment by pengchy** [comment]
I have successfully sorted the gtf using gtf.py. But failed using the GUI on the windows platform.

**Comment by ctokheim** [comment]
Can you post the error message from the log file (an error message pop-up should tell you the path)?

**Comment by pengchy** [comment]
2015-05-20 16:55:15,976 Sort GTF cmd: java -jar -Xmx1536m "bin/SortGtf.jar" "F:\project\05.Primer\gene.ids.gtf" "F:\project\\05.Primer\aa.gtf"
2015-05-20 16:55:16,200 Traceback:
Traceback (most recent call last):
  File "C:\Users\Collin\Documents\GitHub\PrimerSeq\build\pyi.win32\PrimerApp\out00-PYZ.pyz\custom_thread", line 53, in run
  File "C:\Users\Collin\Documents\GitHub\PrimerSeq\build\pyi.win32\PrimerApp\out00-PYZ.pyz\custom_dialog", line 572, in sort_gtf
  File "C:\Users\Collin\Documents\GitHub\PrimerSeq\build\pyi.win32\PrimerApp\out00-PYZ.pyz\subprocess", line 540, in check_call
CalledProcessError: Command 'java -jar -Xmx1536m "bin/SortGtf.jar" "F:\project\\05.Primer\gene.ids.gtf" "F:\project\05.Primer\aa.gtf"' returned non-zero exit status 1

**Comment by ctokheim** [comment]
It may be helpful for you to open the terminal and execute the command that failed so that we get a more informative message. Can you open up the cmd terminal (search for cmd), and then change directories to the PrimerSeq application (type `cd C:\PATH\TO\PRIMERSEQ\INSTALL`, where the PrimerSeq path is found somewhere in your program files). Then execute the single line command that failed:

```bash
java -jar -Xmx1536m "bin/SortGtf.jar" "F:\project\05.Primer\gene.ids.gtf" "F:\project\05.Primer\aa.gtf"
```

It will likely give you a more informative error message which you can post.

**Comment by pengchy** [comment]
Hi ctokheim,

I have tested according to your suggestions. But got the following error:

> java -Xmx890m "bin/SortGtf.jar" "test_data/gene.ids.gtf" "test_data/aa.gtf"
“Could not find or load main class”  bin.SortGtf.jar

Thank you.

**Comment by ctokheim** [comment]
Hmm, I want to make sure the test not a problem with windows using backslash ("\") in file paths versus forwardslash ("/") used by linux and mac os x. Can you replace the "/" with "\"? If we can't figure it out, you can email me the test data at primerseq@gmail.com so I can see what's happening.

**Comment by pengchy** [comment]
Hi ctokheim,

I have sent the test data to primerseq@gmail.com.

Thank you.
