### ISSUE TITLE
error when load gtf files

### ISSUE THREAD

**Issue by noahpieta** [ctokheim/PrimerSeq#45]
hello! i have a problem when i load the gtf file to primerseq

the log says that :
2016-01-06 14:11:01,226 Checking if GTF file is sorted  . . .
2016-01-06 14:11:01,226 Traceback:
Traceback (most recent call last):
  File "C:\Users\Collin\Documents\GitHub\PrimerSeq\build\pyi.win32\PrimerApp\out00-PYZ.pyz\custom_thread", line 72, in run
  File "C:\Users\Collin\Documents\GitHub\PrimerSeq\build\pyi.win32\PrimerApp\out00-PYZ.pyz\primer", line 69, in gene_annotation_reader
  File "C:\Users\Collin\Documents\GitHub\PrimerSeq\build\pyi.win32\PrimerApp\out00-PYZ.pyz\gtf", line 100, in is_gtf_sorted
  File "C:\Users\Collin\Documents\GitHub\PrimerSeq\build\pyi.win32\PrimerApp\out00-PYZ.pyz\gtf", line 73, in is_sorted
  File "C:\Users\Collin\Documents\GitHub\PrimerSeq\build\pyi.win32\PrimerApp\out00-PYZ.pyz\gtf", line 80, in gtf_compare
  File "C:\Users\Collin\Documents\GitHub\PrimerSeq\build\pyi.win32\PrimerApp\out00-PYZ.pyz\gtf", line 82, in <lambda>
KeyError: 'transcript_id'

i download the gtf files from flybase and ensemble. i think it's standard. but it doesn't work.
would you help me to solve it ? 
thank you very much!

**Comment by ctokheim** [comment]
Have you tried removing header lines from the GTF file that start with "#" character? My guess is that it is not correctly parsing those, although you could paste in the top 10-20 lines and I may have a better idea.

**Comment by noahpieta** [comment]
there is no annotation line (lines with # at left terminal) in my GTF. i give a part of the gtf for you.

3R      FlyBase exon    16935927        16936104        11      -       .       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id "FBtr033
0709"; transcript_symbol "Abd-B-RF";
3R      FlyBase exon    16931402        16931613        11      -       .       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id "FBtr033
0709"; transcript_symbol "Abd-B-RF";
3R      FlyBase exon    16931116        16931317        11      -       .       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id "FBtr033
0709"; transcript_symbol "Abd-B-RF";
3R      FlyBase exon    16929638        16929852        11      -       .       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id "FBtr033
0709"; transcript_symbol "Abd-B-RF";
3R      FlyBase exon    16927667        16929580        11      -       .       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id "FBtr033
0709"; transcript_symbol "Abd-B-RF";
3R      FlyBase start_codon     16931603        16931605        .       -       0       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id
"FBtr0330709"; transcript_symbol "Abd-B-RF";
3R      FlyBase CDS     16931402        16931605        11      -       0       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id "FBtr033
0709"; transcript_symbol "Abd-B-RF"; # SO:0000697:gene_with_stop_codon_read_through
3R      FlyBase CDS     16931116        16931317        11      -       0       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id "FBtr033
0709"; transcript_symbol "Abd-B-RF"; # SO:0000697:gene_with_stop_codon_read_through
3R      FlyBase CDS     16929638        16929852        11      -       2       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id "FBtr033
0709"; transcript_symbol "Abd-B-RF"; # SO:0000697:gene_with_stop_codon_read_through
3R      FlyBase stop_codon      16929341        16929343        .       -       0       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id
"FBtr0330709"; transcript_symbol "Abd-B-RF";
3R      FlyBase 3UTR    16927667        16929340        11      -       .       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id "FBtr033
0709"; transcript_symbol "Abd-B-RF";
3R      FlyBase mRNA    16927667        16944273        11      -       .       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id "FBtr034
6764"; transcript_symbol "Abd-B-RG";
3R      FlyBase 5UTR    16943782        16944273        11      -       .       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id "FBtr034
6764"; transcript_symbol "Abd-B-RG";
3R      FlyBase 5UTR    16943253        16943299        11      -       .       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id "FBtr034
6764"; transcript_symbol "Abd-B-RG";
3R      FlyBase 5UTR    16935927        16936104        11      -       .       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id "FBtr034
6764"; transcript_symbol "Abd-B-RG";
3R      FlyBase 5UTR    16931606        16931613        11      -       .       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id "FBtr034
6764"; transcript_symbol "Abd-B-RG";
3R      FlyBase exon    16943782        16944273        11      -       .       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id "FBtr034
6764"; transcript_symbol "Abd-B-RG";
3R      FlyBase exon    16943253        16943299        11      -       .       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id "FBtr034
6764"; transcript_symbol "Abd-B-RG";
3R      FlyBase exon    16935927        16936104        11      -       .       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id "FBtr034
6764"; transcript_symbol "Abd-B-RG";
3R      FlyBase exon    16931402        16931613        11      -       .       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id "FBtr034
6764"; transcript_symbol "Abd-B-RG";
3R      FlyBase exon    16931116        16931317        11      -       .       gene_id "FBgn0000015"; gene_symbol "Abd-B"; transcript_id "FBtr034
6764"; transcript_symbol "Abd-B-RG";


i also attached the gtf . waiting for your good message!

thank you very much!

[head200gtf.txt](https://github.com/ctokheim/PrimerSeq/files/80767/head200gtf.txt)

**Comment by ctokheim** [comment]
I tested your GTF, and it looks like the error was because the GTF file was not sorted (http://primerseq.sourceforge.net/gtf.html). Since it may be beneficial for others too, if you could point me to where you obtained the GTF file I could sort the GTF and post it on the PrimerSeq website.

**Comment by noahpieta** [comment]
thank you for answering ! the gtf is from flybase: ftp://ftp.flybase.net/releases/current/dmel_r6.08 under the gtf folder. 
i have try to sort it but it didn't work. report like this when i checked the gtf:

xuyz@a713:~> python xyz_zy/primerseq/gtf.py -c /public1/xuyz/xyz_zy/flybase/dmel_r6.08/dmel-all-r6.08.gtf
Traceback (most recent call last):
  File "xyz_zy/primerseq/gtf.py", line 130, in <module>
    if is_gtf_sorted(args.is_sorted):
  File "xyz_zy/primerseq/gtf.py", line 100, in is_gtf_sorted
    return is_sorted(mygtf_reader, gtf_compare)
  File "xyz_zy/primerseq/gtf.py", line 73, in is_sorted
    return all(imap(compare, a, b))
  File "xyz_zy/primerseq/gtf.py", line 80, in gtf_compare
    srt_list = sorted(tmp_list, key=lambda x: (x.seqname,
  File "xyz_zy/primerseq/gtf.py", line 82, in <lambda>
    x.attribute['transcript_id'],
KeyError: 'transcript_id'

thank you very much for your help!!!!
best!

**Comment by ctokheim** [comment]
I have sorted the GTF file and posted the link for downloading it on the PrimerSeq website (http://sourceforge.net/projects/primerseq/files/GTF/Drosophila_melanogaster.flybase.r6.08.sorted.gtf.gz/download). I'm looking into the parsing issue with Flybase GTF, but hopefully that GTF can get you up and running. I have tested the GTF file, but let me know if it doesn't work for you.

**Comment by noahpieta** [comment]
i'm trying it and it works well ! thank you very much !!!

**Comment by ctokheim** [comment]
Great to hear!
