### ISSUE TITLE
error when loading gtf files

### ISSUE THREAD

**Issue by feedmewifi** [ctokheim/PrimerSeq#48]
when I try and load a gtf I get this in the log:
```
2020-08-03 18:27:14,144 Checking if GTF file is sorted  . . .
2020-08-03 18:27:14,171 Traceback:
Traceback (most recent call last):
  File "C:\Users\Collin\Documents\GitHub\PrimerSeq\build\PrimerApp\out00-PYZ.pyz\custom_thread", line 72, in run
  File "C:\Users\Collin\Documents\GitHub\PrimerSeq\build\PrimerApp\out00-PYZ.pyz\primer", line 69, in gene_annotation_reader
  File "C:\Users\Collin\Documents\GitHub\PrimerSeq\build\PrimerApp\out00-PYZ.pyz\gtf", line 99, in is_gtf_sorted
  File "C:\Users\Collin\Documents\GitHub\PrimerSeq\build\PrimerApp\out00-PYZ.pyz\gtf", line 72, in is_sorted
  File "C:\Users\Collin\Documents\GitHub\PrimerSeq\build\PrimerApp\out00-PYZ.pyz\gtf", line 79, in gtf_compare
  File "C:\Users\Collin\Documents\GitHub\PrimerSeq\build\PrimerApp\out00-PYZ.pyz\gtf", line 81, in <lambda>
KeyError: 'transcript_id'
```
it's sorted, and there's not commented lines at the top.

**Comment by ctokheim** [comment]
Hmm. Could you attach or provide a link to your GTF file? That way I can try to debug what went wrong.

**Comment by feedmewifi** [comment]
Yes, you can find it here from ensembl: ftp://ftp.ensembl.org/pub/release-100/gtf/rattus_norvegicus/Rattus_norvegicus.Rnor_6.0.100.gtf.gz

**Comment by SandyChenn** [comment]
when I try and load a gtf file (named 'Homo_sapiens.knownGene.hg19.sorted.withGenes.gtf' ) which is downloaded according to the user tutorial (https://primerseq.sourceforge.net/user_tutorial.html) , I get an error like this:

<img width="362" alt="2023-03-28_17h26_15" src="https://user-images.githubusercontent.com/128274346/228283740-152d8e23-37a1-454c-8f88-8c72406fb1ee.png">

And the log file is
 "2023-03-28 22:52:09,733 Error: <type 'exceptions.UnicodeEncodeError'>'ascii' codec can't encode characters in position 10-13: ordinal not in range(128)
2023-03-28 22:52:09,733 Traceback:
  File "<string>", line 612, in on_choose_gtf_button
  File "<string>", line 631, in set_gtf"


I have installed JRE at first, and I don't konw how to deal with it. 
Could you help me? Thank you very much!
